### ISSUE TITLE
Zuma Agave Package

### ISSUE THREAD

**Issue by kespinola** [abk-labs/zuma#2]
## Goal
Bundle agave client into Debian package.

## Requirements
- A build method which is suited for automation.
- Ability to bundle agave binary and startup config together which can be overwritten by operator.
- Can be used to build other rust based OS clients.

## Resources
- https://github.com/kornelski/cargo-deb

**Comment by FarinM** [comment]
# cargo-deb build instructions

```
sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler
```

```
rustup update
cargo install cargo-deb
```

Replace with preferred version
```
git clone https://github.com/anza-xyz/agave
cd agave
git checkout v1.18.15
```

```
cargo deb -p agave-validator
dpkg -i ./target/debian/agave-validator_1.18.15-1_amd64.deb
```
