### ISSUE TITLE
Zuma Genesis

### ISSUE THREAD

**Issue by kespinola** [abk-labs/zuma#5]
## Objectives
- The organization bootstrapping the SVM network can set the economics of the network.
 - Bootstrapping and treasury workflows for the network’s native token.

**Comment by kespinola** [comment]
Zumanet is a 0 fee 0 rewards only supporting stake weighted connection. The native token still remains SOL.

**Comment by FarinM** [comment]
## Original Command

```bash
solana-genesis \
  --ledger <ledger_dir> \
  --faucet-pubkey <faucet-pubkey> \
  --bootstrap-validator \
    <identity-account> \
    <vote-account> \
    <stake-account> \
  --faucet-lamports <lamports> \
  --target-lamports-per-signature 0 \
  --inflation none \
  --lamports-per-byte-year 1 \
  --slots-per-epoch 150 \
  --cluster-type development 
```
# Zuma CLI

- Automatically generate bootstrap validator accounts.
- Set a default ledger location.
- Create preset configurations for common setups.
