### ISSUE TITLE
Zumanet Benchmarking

### ISSUE THREAD

**Issue by kespinola** [abk-labs/zuma#9]
### Goal
Performance benchmarking of zumanet using benchmark-tps.

https://github.com/anza-xyz/agave/tree/5263c9d61f3af060ac995956120bef11c1bbf182/bench-tps

**Comment by FarinM** [comment]
# Zumanet Benchmarking with solana-bench-tps

The following can be used to run a benchmark:

```bash
solana-bench-tps \
  --entrypoint <GOSSIP_ENTRYPOINT> \
  --tx-count 50000 \
  --client-node-id <PATH_TO_KEYPAIR> \
  --url <RPC_URL> \
  --thread-batch-sleep-ms 0 \
  --duration 30 
```

`--client-node-id <PATH_TO_KEYPAIR>`
Path to keypair JSON file of a validator with delegated stake - Used to establish a staked connection

`--url <RPC_URL>`
RPC URL for the Solana cluster. Doesn't need to match the client-node-id validator, but must be provided.

**Comment by kespinola** [comment]
Thanks @FarinM what I'd like to do is re-export the benchmark lib through the zuma cli. The zuma wrapper should be able to discover variables like entrypoint, client-node-id, and url. The rest should have sensible defaults. This way instead of passing all these arguments operators run `zuma bench`

**Comment by FarinM** [comment]
# Initail Zumanet Benchmark Results

## Test Configuration
- Duration: 90 seconds per run
- Number of runs: 3

## Results

| Run | Max TPS | Average TPS |
|-----|---------|-------------|
| 1   | 74,778  | 30,270.098  |
| 2   | 74,915  | 24,950.688  |
| 3   | 74,902  | 29,673.377  |

## Summary
- Highest Max TPS: 74,915 (Run 2)
- Highest Average TPS: 30,270.098 (Run 1)
- Overall Average TPS: 28,298.054
